# memory_layer_kg.py
# NOTE: Generated by ChatGPT per user's requested modifications.
from __future__ import annotations

from typing import Callable, List, Dict, Optional, Literal, Any, Union, Tuple
import json
from datetime import datetime
import uuid
from sentence_transformers import SentenceTransformer
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.cluster import DBSCAN
import os
from abc import ABC, abstractmethod
from nltk.tokenize import word_tokenize
from dataclasses import dataclass, field
import difflib
import re
from dotenv import load_dotenv
import time

from litellm import completion  # used by OllamaController

# Keep existing prompts import (do NOT change prompts here unless explicitly noted)
from prompt import *  # noqa: F401,F403

load_dotenv()
os.environ["TRANSFORMERS_OFFLINE"] = "1"

ExperienceType = Literal["fact", "strategy", "preference", "procedure"]


# =========================
# Data structures
# =========================

@dataclass
class Entity:
    """图谱中的实体节点 V"""
    id: str
    name: str
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class Relation:
    """图谱中的边 E"""
    id: str
    source: str
    target: str
    relation_type: str
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class QAItem:
    id: str
    question: str
    answer: str
    emb: np.ndarray
    speaker: str
    timestamp: Optional[str] = None


@dataclass
class ExperienceItem:
    id: str
    type: ExperienceType
    content: str
    source_qa_ids: List[str]
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class Cluster:
    id: str
    cluster_center: List[str]
    vector_center: np.ndarray
    center_text: str
    QAList: List[QAItem] = field(default_factory=list)
    ExpList: List[ExperienceItem] = field(default_factory=list)
    add_buffer: List[QAItem] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)


# =========================
# Utilities
# =========================

def dbscan_clustering_func(
    emb_matrix: np.ndarray,
    eps: float = 0.3,
    min_samples: int = 2,
) -> List[int]:
    """
    使用 DBSCAN 对向量做聚类，返回长度为 N 的标签列表。
    metric='cosine' 适合语义向量。
    """
    db = DBSCAN(
        eps=eps,
        min_samples=min_samples,
        metric="cosine"
    )
    labels = db.fit_predict(emb_matrix)
    return labels.tolist()


def simple_tokenize(text: str):
    return word_tokenize(text)


# =========================
# LLM controllers
# =========================

class BaseLLMController(ABC):
    @abstractmethod
    def get_completion(
        self,
        prompt: str,
        response_format: Optional[dict] = None,
        temperature: float = 0.7,
    ) -> str:
        pass


class OpenAIController(BaseLLMController):
    def __init__(self, model: str, api_key: Optional[str] = None):
        from openai import OpenAI
        api_key = api_key or os.getenv("OPENAI_API_KEY")

        if not api_key:
            raise ValueError("Missing OpenAI API key.")

        self.model = model
        self.client = OpenAI(
            api_key=api_key,
            base_url=os.getenv("OPENAI_BASE_URL"),
        )

    def get_completion(
        self,
        prompt: str,
        response_format: Optional[dict] = None,
        temperature: float = 0.7,
    ) -> str:

        system_msg = (
            "You must respond with a JSON object that matches the schema."
            if response_format else
            "You are a helpful assistant."
        )

        # Deepseek-like models may need schema constraints appended
        if self.model.startswith("deepseek") and response_format:
            prompt = append_schema_constraints_to_prompt(prompt, response_format)  # noqa: F405

        messages = [
            {"role": "system", "content": system_msg},
            {"role": "user", "content": prompt},
        ]

        kwargs = {
            "model": self.model,
            "messages": messages,
            "temperature": temperature,
            "max_tokens": 4000,
        }

        if response_format and not self.model.startswith("deepseek"):
            kwargs["response_format"] = response_format

        resp = self.client.chat.completions.create(**kwargs)
        return resp.choices[0].message.content


class OllamaController(BaseLLMController):
    def __init__(self, model: str):
        self.model = model

    def _empty_value(self, t: str) -> Any:
        return {"array": [], "string": "", "object": {}, "number": 0, "boolean": False}.get(t, None)

    def _empty_schema_response(self, fmt: dict) -> dict:
        schema = fmt["json_schema"]["schema"]
        props = schema.get("properties", {})
        return {name: self._empty_value(p["type"]) for name, p in props.items()}

    def get_completion(
        self,
        prompt: str,
        response_format: Optional[dict] = None,
        temperature: float = 0.7,
    ) -> str:

        system_msg = (
            "You must respond with a JSON object that matches the schema."
            if response_format else
            "You are a helpful assistant."
        )
        # if "qwen3" in self.model.lower():
            # prompt+="/no_think"
            # print("-------------------Using Qwen3 model with /no_think directive.")

        try:
            if "qwen3" in self.model.lower():
                kwargs = {
                    "model": f"ollama_chat/{self.model}",
                    "messages": [
                        {"role": "system", "content": system_msg},
                        {"role": "user", "content": prompt},
                    ],
                    "temperature": temperature,
                    "think": False,
                }
            else:
                kwargs = {
                    "model": f"ollama_chat/{self.model}",
                    "messages": [
                        {"role": "system", "content": system_msg},
                        {"role": "user", "content": prompt},
                    ],
                    "temperature": temperature,
                }

            if response_format:
                kwargs["response_format"] = response_format

            resp = completion(**kwargs)
            return resp.choices[0].message.content

        except Exception:
            if response_format:
                return json.dumps(self._empty_schema_response(response_format), ensure_ascii=False)
            raise


class LLMController:
    def __init__(
        self,
        backend: Literal["openai", "ollama"],
        model: str,
        api_key: Optional[str] = None,
    ):
        if backend == "openai":
            self.llm = OpenAIController(model=model, api_key=api_key)
        elif backend == "ollama":
            self.llm = OllamaController(model=model)
        else:
            raise ValueError("Backend must be one of: openai, ollama")


# =========================
# Knowledge Graph
# =========================

class KnowledgeGraph:
    """
    G = (V, E)
    V: Entity
    E: Relation
    """
    def __init__(self):
        self.entities: Dict[str, Entity] = {}
        self.relations: Dict[str, Relation] = {}
        self.name_index: Dict[str, str] = {}
        self.out_edges: Dict[str, List[str]] = {}
        self.in_edges: Dict[str, List[str]] = {}

    def _normalize_name(self, name: str) -> str:
        return name.strip().lower()

    def _index_entity_names(self, entity: Entity):
        all_names = [entity.name]
        aliases = entity.metadata.get("aliases") or []
        if isinstance(aliases, list):
            for a in aliases:
                if isinstance(a, str) and a.strip():
                    all_names.append(a.strip())

        for n in all_names:
            key = self._normalize_name(n)
            if key and key not in self.name_index:
                self.name_index[key] = entity.id

    def add_entity(
        self,
        name: str,
        metadata: Optional[Dict[str, Any]] = None,
        entity_id: Optional[str] = None
    ) -> str:
        if metadata is None:
            metadata = {}

        eid = entity_id or str(uuid.uuid4())

        entity = Entity(
            id=eid,
            name=name,
            metadata=metadata
        )
        self.entities[eid] = entity

        self.out_edges.setdefault(eid, [])
        self.in_edges.setdefault(eid, [])
        self._index_entity_names(entity)

        return eid

    def add_entity_node(self, name: str, metadata: Optional[Dict[str, Any]] = None) -> str:
        meta = metadata or {}
        meta.setdefault("node_type", "entity")
        meta.setdefault("aliases", [])
        return self.add_entity(name=name, metadata=meta)

    def add_passage_node(self, text: str, metadata: Optional[Dict[str, Any]] = None) -> str:
        meta = metadata or {}
        meta.setdefault("node_type", "passage")

        return self.add_entity(name=text, metadata=meta)

    def add_experience_node(self, text: str, metadata: Optional[Dict[str, Any]] = None) -> str:
        meta = metadata or {}
        meta.setdefault("node_type", "experience")
        return self.add_entity(name=text, metadata=meta)

    def get_entity(self, key: str) -> Optional[Entity]:
        if key in self.entities:
            return self.entities[key]

        norm = self._normalize_name(key)
        if norm in self.name_index:
            eid = self.name_index[norm]
            return self.entities.get(eid)

        return None

    def get_or_add_entity(
        self,
        name: str,
        metadata: Optional[Dict[str, Any]] = None
    ) -> str:
        existing = self.get_entity(name)
        if existing is not None:
            # 可更新 metadata 的别名
            if metadata:
                # 合并 aliases
                if "aliases" in metadata and isinstance(metadata["aliases"], list):
                    exist_alias = existing.metadata.get("aliases") or []
                    if not isinstance(exist_alias, list):
                        exist_alias = []
                    for a in metadata["aliases"]:
                        if isinstance(a, str) and a.strip() and a not in exist_alias:
                            exist_alias.append(a)
                    existing.metadata["aliases"] = exist_alias
                    # 重新索引
                    self._index_entity_names(existing)
            return existing.id
        return self.add_entity(name=name,  metadata=metadata or {})

    def add_relation(
        self,
        source_id: str,
        target_id: str,
        relation_type: str,
        metadata: Optional[Dict[str, Any]] = None,
        relation_id: Optional[str] = None
    ) -> str:
        if metadata is None:
            metadata = {}

        if source_id not in self.entities:
            raise ValueError(f"source entity {source_id} not found")
        if target_id not in self.entities:
            raise ValueError(f"target entity {target_id} not found")

        rid = relation_id or str(uuid.uuid4())
        rel = Relation(
            id=rid,
            source=source_id,
            target=target_id,
            relation_type=relation_type,
            metadata=metadata
        )
        self.relations[rid] = rel

        self.out_edges.setdefault(source_id, []).append(rid)
        self.in_edges.setdefault(target_id, []).append(rid)

        return rid

    def get_neighbour(
        self,
        entity_id: str,
        max_hop: int = 1,
        include_passages: bool = False,
        include_experiences: bool = False,
    ) -> Dict[str, List[Any]]:

        if entity_id not in self.entities:
            return {"entities": [], "relations": []}

        visited_entities: set[str] = {entity_id}
        visited_relations: set[str] = set()

        # passages
        if include_passages:
            for rid in self.in_edges.get(entity_id, []):
                rel = self.relations.get(rid)
                if not rel or rel.relation_type != "contains":
                    continue
                src_ent = self.entities.get(rel.source)
                if src_ent and src_ent.metadata.get("node_type") == "passage":
                    visited_entities.add(src_ent.id)
                    visited_relations.add(rid)

        # experiences
        if include_experiences:
            for rid in self.in_edges.get(entity_id, []):
                rel = self.relations.get(rid)
                if not rel or rel.relation_type != "about":
                    continue
                src_ent = self.entities.get(rel.source)
                if src_ent and src_ent.metadata.get("node_type") == "experience":
                    visited_entities.add(src_ent.id)
                    visited_relations.add(rid)

        frontier: set[str] = {entity_id}
        for _ in range(max_hop):
            new_frontier: set[str] = set()
            for eid in list(frontier):
                for rid in self.out_edges.get(eid, []):
                    rel = self.relations.get(rid)
                    if not rel:
                        continue
                    if rel.relation_type in ("contains", "about", "src_of", "tgt_of", "time_of"):
                        continue

                    tgt_ent = self.entities.get(rel.target)
                    if not tgt_ent:
                        continue
                    if tgt_ent.metadata.get("node_type", "entity") != "entity":
                        continue

                    visited_relations.add(rid)
                    if tgt_ent.id not in visited_entities:
                        visited_entities.add(tgt_ent.id)
                        new_frontier.add(tgt_ent.id)

                for rid in self.in_edges.get(eid, []):
                    rel = self.relations.get(rid)
                    if not rel:
                        continue
                    if rel.relation_type in ("contains", "about", "src_of", "tgt_of", "time_of"):
                        continue

                    src_ent = self.entities.get(rel.source)
                    if not src_ent:
                        continue
                    if src_ent.metadata.get("node_type", "entity") != "entity":
                        continue

                    visited_relations.add(rid)
                    if src_ent.id not in visited_entities:
                        visited_entities.add(src_ent.id)
                        new_frontier.add(src_ent.id)

            frontier = new_frontier
            if not frontier:
                break

        entities = [self.entities[eid] for eid in visited_entities]
        relations = [self.relations[rid] for rid in visited_relations]

        return {"entities": entities, "relations": relations}

    # --- dynamic merge/update utilities ---

    def merge_entities(
        self,
        keep_eid: str,
        remove_eid: str,
        alias: Optional[str] = None
    ) -> bool:
        """
        Merge 'remove_eid' into 'keep_eid':
        - redirect all relations touching remove_eid to keep_eid
        - delete remove entity and its adjacency lists
        - add alias into keep entity metadata.aliases (optional)
        Returns True if merged successfully.
        """
        if keep_eid == remove_eid:
            return False
        if keep_eid not in self.entities or remove_eid not in self.entities:
            return False

        keep_ent = self.entities[keep_eid]
        rem_ent = self.entities[remove_eid]

        if alias and isinstance(alias, str) and alias.strip():
            aliases = keep_ent.metadata.get("aliases") or []
            if not isinstance(aliases, list):
                aliases = []
            if alias not in aliases:
                aliases.append(alias)
            keep_ent.metadata["aliases"] = aliases

        # Also add removed name as alias
        rem_name = rem_ent.name
        if rem_name and rem_name != keep_ent.name:
            aliases = keep_ent.metadata.get("aliases") or []
            if not isinstance(aliases, list):
                aliases = []
            if rem_name not in aliases:
                aliases.append(rem_name)
            keep_ent.metadata["aliases"] = aliases

        # Re-index keep entity names (and aliases)
        self._index_entity_names(keep_ent)

        # Redirect relations
        # Note: We do NOT deduplicate relations here (per user request).
        for rid, rel in list(self.relations.items()):
            changed = False
            if rel.source == remove_eid:
                rel.source = keep_eid
                changed = True
            if rel.target == remove_eid:
                rel.target = keep_eid
                changed = True
            if changed:
                # fix adjacency: remove rid from old lists, add to new
                # old adjacency might not contain due to earlier inconsistencies; safe remove
                if rid in self.out_edges.get(remove_eid, []):
                    self.out_edges[remove_eid].remove(rid)
                if rid in self.in_edges.get(remove_eid, []):
                    self.in_edges[remove_eid].remove(rid)

                self.out_edges.setdefault(rel.source, [])
                self.in_edges.setdefault(rel.target, [])
                if rid not in self.out_edges[rel.source]:
                    self.out_edges[rel.source].append(rid)
                if rid not in self.in_edges[rel.target]:
                    self.in_edges[rel.target].append(rid)

        # Delete entity
        self.entities.pop(remove_eid, None)
        self.out_edges.pop(remove_eid, None)
        self.in_edges.pop(remove_eid, None)

        # Remove from name_index any mapping pointing to removed_eid
        for k, v in list(self.name_index.items()):
            if v == remove_eid:
                self.name_index.pop(k, None)

        return True

    def dedup_relations_ignore_condition(
        self,
        keep: str = "first",          # "first" or "latest"
        include_time: bool = True,    # True: (src, type, tgt, time) / False: (src, type, tgt)
    ) -> int:
        """
        全量去重 KG.relations，忽略 condition。
        去重 key:
          - include_time=True  -> (source, relation_type, target, time)
          - include_time=False -> (source, relation_type, target)

        keep:
          - "first": 保留最先出现的 relation（遍历顺序）
          - "latest": 保留 time 更“长/非空”的那条（简单启发式；不解析时间戳）
        返回：删除的重复 relation 数量
        """

        if not self.relations:
            return 0

        def _time_of(rel) -> str:
            try:
                return str((rel.metadata or {}).get("time", "")).strip()
            except Exception:
                return ""

        # 1) 找出要保留的 relation（以及要删的）
        key_to_keep_id: Dict[Tuple, str] = {}
        to_delete: List[str] = []

        for rid, rel in list(self.relations.items()):
            t = _time_of(rel) if include_time else ""
            key = (rel.source, rel.relation_type, rel.target, t) if include_time else (rel.source, rel.relation_type, rel.target)

            if key not in key_to_keep_id:
                key_to_keep_id[key] = rid
                continue

            # 已有同 key 的 relation：决定保留谁
            keep_id = key_to_keep_id[key]
            keep_rel = self.relations.get(keep_id)

            if keep == "latest" and keep_rel is not None:
                # 启发式：优先保留 time 更“信息量大”的（非空、长度更长）
                t_keep = _time_of(keep_rel)
                t_cur = _time_of(rel)
                score_keep = (1 if t_keep else 0, len(t_keep))
                score_cur = (1 if t_cur else 0, len(t_cur))

                if score_cur > score_keep:
                    # 换保留对象：旧的标记删除
                    to_delete.append(keep_id)
                    key_to_keep_id[key] = rid
                else:
                    to_delete.append(rid)
            else:
                # 默认 keep="first"
                to_delete.append(rid)

        if not to_delete:
            return 0

        # 2) 真正删除 relation，并维护 out_edges / in_edges
        for rid in to_delete:
            rel = self.relations.pop(rid, None)
            if not rel:
                continue

            # out_edges
            outs = self.out_edges.get(rel.source)
            if outs and rid in outs:
                outs.remove(rid)

            # in_edges
            ins = self.in_edges.get(rel.target)
            if ins and rid in ins:
                ins.remove(rid)

        return len(to_delete)


# =========================
# QAS Manager
# =========================

class QASManager:
    def __init__(self, emb_model_name: str):
        self._items: Dict[str, QAItem] = {}
        self.emb_model = SentenceTransformer(emb_model_name)

    def add(self, qa: QAItem) -> None:
        self._items[qa.id] = qa

    def get_embedding(self, text: str) -> np.ndarray:
        emb = self.emb_model.encode([text])[0]
        return emb

    def create(
        self,
        question: str,
        answer: str,
        speaker: str,
        time_str: Optional[str] = None,
        emb: Optional[np.ndarray] = None,
        qa_id: Optional[str] = None
    ) -> QAItem:
        if time_str is None:
            time_str = datetime.utcnow().isoformat()

        if emb is None:
            qa = question + " " + answer
            emb = self.get_embedding(qa)

        qa_item = QAItem(
            id=qa_id or str(uuid.uuid4()),
            question=question,
            answer=answer,
            emb=emb,
            speaker=speaker,
            timestamp=time_str
        )
        self.add(qa_item)
        return qa_item

    def get(self, qa_id: str) -> Optional[QAItem]:
        return self._items.get(qa_id)

    def remove(self, qa_id: str) -> None:
        self._items.pop(qa_id, None)

    def __len__(self) -> int:
        return len(self._items)


@dataclass
class PassageDoc:
    # 只负责：原文检索结果 + speaker/timestamp
    text: str
    timestamp: str
    speaker: Optional[str] = None
    qa_id: Optional[str] = None


class PassageRetriever:
    """
    全局 passage 检索器：
    - 只索引原文 text
    - search 返回 PassageDoc（带 speaker/timestamp）
    """
    def __init__(self, model_name: str = "all-MiniLM-L6-v2"):
        self.model = SentenceTransformer(model_name)
        self.docs: List[PassageDoc] = []
        self.embeddings: Optional[np.ndarray] = None

    def clear(self):
        self.docs = []
        self.embeddings = None

    def add_docs(self, docs: List[PassageDoc]):
        if not docs:
            return
        filtered = []
        for d in docs:
            if not isinstance(d, PassageDoc):
                continue
            if not isinstance(d.text, str) or not d.text.strip():
                continue
            if d.timestamp is None:
                d.timestamp = ""
            filtered.append(d)

        if not filtered:
            return

        texts = [d.text for d in filtered]
        new_embs = self.model.encode(texts)

        if self.embeddings is None or len(self.docs) == 0:
            self.docs = filtered
            self.embeddings = new_embs
        else:
            self.docs.extend(filtered)
            self.embeddings = np.vstack([self.embeddings, new_embs])

    def search(self, query: str, k: int = 6) -> List[PassageDoc]:
        if not self.docs or self.embeddings is None:
            return []
        q_emb = self.model.encode([query])[0]
        sims = cosine_similarity([q_emb], self.embeddings)[0]
        topk = min(k, len(self.docs))
        idxs = np.argsort(sims)[-topk:][::-1]
        return [self.docs[i] for i in idxs]





# =========================
# Agentic Memory System
# =========================

class AgenticMemorySystem:
    def __init__(
        self,
        model_name: str = 'all-MiniLM-L6-v2',
        llm_backend: str = "ollama",
        llm_model: str = "gpt-4o-mini",
        api_key: Optional[str] = None,
        api_base: Optional[str] = None,
        sglang_host: str = "http://localhost",
        sglang_port: int = 30000
    ):

        self._clusters: Dict[str, Cluster] = {}
        self.retriever = PassageRetriever(model_name)

        self._embed_model = self.retriever.model
        self.kg = KnowledgeGraph()
        self.llm_controller = LLMController(llm_backend, llm_model, api_key)

        self._triple_ids: List[str] = []
        self._triple_texts: List[str] = []
        self._triple_embs: Optional[np.ndarray] = None
        self.pending_qas: List[QAItem] = []
        self._qa_meta: Dict[str, Dict[str, str]] = {}
        self._qa_time_hint_cache: Dict[str, str] = {}
        self._text_emb_cache:Dict[str,np.ndarray]={}


    # ---------- math helpers ----------
    def sim_fn(self, emb1: np.ndarray, emb2: np.ndarray) -> float:
        denom = (np.linalg.norm(emb1) * np.linalg.norm(emb2)) + 1e-8
        return float(np.dot(emb1, emb2) / denom)

    def embed_text(self, text: str) -> np.ndarray:
        return self._embed_model.encode([text])[0]

    def _get_cached_embs(self, keys: List[str], texts: List[str]) -> np.ndarray:
        """
        keys 与 texts 一一对应：
        - key 优先用稳定 id（例如 qa_id），否则回退到文本本身
        - 未命中的一次性 batch encode 后写入缓存
        """
        assert len(keys) == len(texts)
        not_cached_idx = [i for i, k in enumerate(keys) if k not in self._text_emb_cache]

        if not_cached_idx:
            to_encode = [texts[i] for i in not_cached_idx]
            new_embs = self._embed_model.encode(to_encode)
            for off, i in enumerate(not_cached_idx):
                self._text_emb_cache[keys[i]] = new_embs[off]

        return np.stack([self._text_emb_cache[k] for k in keys], axis=0)


    # ---------- robust json parsing ----------
    def _safe_json_from_raw(self, raw: Any) -> dict:
        if isinstance(raw, dict):
            return raw
        if not isinstance(raw, str):
            return {}
        s = raw.strip()
        if not s:
            return {}
        if "{" in s and "}" in s:
            s = s[s.find("{"): s.rfind("}") + 1]
        s = s.replace("\n", " ").replace("\r", " ")
        s = re.sub(r",\s*}", "}", s)
        s = re.sub(r",\s*]", "]", s)
        try:
            return json.loads(s)
        except Exception:
            return {}

    def _llm_json(
        self,
        prompt: str,
        response_format: dict,
        temperature: float = 0.2,
        max_retries: int = 3,
    ) -> Tuple[dict, str]:
        last_raw = ""
        for retry in range(max_retries):
            try:
                raw = self.llm_controller.llm.get_completion(
                    prompt=prompt,
                    response_format=response_format,
                    temperature=max(0.0, temperature - retry * 0.1)
                )
                last_raw = raw if isinstance(raw, str) else str(raw)
                if last_raw.strip():
                    data = self._safe_json_from_raw(last_raw)
                    print(f"LLM JSON parse attempt {retry + 1}: {data}")
                    if data:
                        return data, last_raw

                if retry < max_retries - 1:
                    continue
            except Exception:
                if retry < max_retries - 1:
                    time.sleep(1)
                    continue
        return {}, last_raw

    # =========================
    # Cluster lifecycle
    # =========================

    def get_cluster(self, cluster_id: str) -> Optional[Cluster]:
        return self._clusters.get(cluster_id)

    def all_clusters(self) -> List[Cluster]:
        return list(self._clusters.values())

    def add_cluster(self, cluster: Cluster) -> None:
        self._clusters[cluster.id] = cluster

    def remove_cluster(self, cluster_id: str) -> None:
        self._clusters.pop(cluster_id, None)

    def get_qas(self, cluster_id: str, strategy: Literal["sample", "all"]) -> List[QAItem]:
        cluster = self.get_cluster(cluster_id)
        if cluster is None:
            raise ValueError("cluster not found")
        if strategy == "sample":
            sample_size = min(5, len(cluster.QAList))
            return cluster.QAList[:sample_size]
        elif strategy == "all":
            return list(cluster.QAList)
        else:
            raise ValueError(f"unknown strategy: {strategy}")

    # ----- clustering & experiences extraction (unchanged prompts) -----

    def initial_clustering(
        self,
        qa_items: List[QAItem],
        clustering_func: Callable[[np.ndarray], List[int]],
        max_recluster_rounds: int = 2,
    ) -> List[Cluster]:
        if not qa_items:
            return []

        remaining = qa_items[:]
        round_idx = 0
        created_clusters: List[Cluster] = []

        while remaining and round_idx <= max_recluster_rounds:
            round_idx += 1

            emb_matrix = np.stack([qa.emb for qa in remaining], axis=0)
            labels = clustering_func(emb_matrix)

            label_to_qas: Dict[int, List[QAItem]] = {}
            for qa, label in zip(remaining, labels):
                label_to_qas.setdefault(label, []).append(qa)

            next_round_qas: List[QAItem] = []

            for _, qas_in_cluster in label_to_qas.items():
                if not qas_in_cluster:
                    continue

                consistency = self._check_cluster_consistency(qas_in_cluster)
                if consistency.get("is_consistent", True):
                    cluster = self.create_cluster(
                        qas_in_cluster,
                        suggested_center_text=consistency.get("label"),
                        consistency_info=consistency,
                    )
                    created_clusters.append(cluster)
                else:
                    next_round_qas.extend(qas_in_cluster)

            remaining = next_round_qas

        self.pending_qas.extend(remaining)
        return created_clusters

    def create_cluster(
        self,
        qa_items: List[QAItem],
        cluster_id: Optional[str] = None,
        k: int = 3,
        suggested_center_text: Optional[str] = None,
        consistency_info: Optional[Dict[str, Any]] = None,
    ) -> Cluster:
        if not qa_items:
            raise ValueError("qa_items 不能为空")

        cid = cluster_id or str(uuid.uuid4())

        emb_matrix = np.stack([qa.emb for qa in qa_items], axis=0)
        vector_center = emb_matrix.mean(axis=0)

        sims = [self.sim_fn(qa.emb, vector_center) for qa in qa_items]
        sorted_idx = np.argsort(sims)[::-1]
        top_k = min(k, len(qa_items))
        cluster_center_ids = [qa_items[i].id for i in sorted_idx[:top_k]]

        cluster = Cluster(
            id=cid,
            cluster_center=cluster_center_ids,
            vector_center=vector_center,
            center_text="",
            QAList=list(qa_items),
            ExpList=[],
            add_buffer=[],
            metadata={}
        )
        self.add_cluster(cluster)

        if consistency_info:
            cluster.metadata["consistency"] = consistency_info

        if suggested_center_text:
            cluster.center_text = suggested_center_text
        elif self.llm_controller is not None:
            cluster.center_text = self.generate_center_text(cluster)

        if self.llm_controller is not None:
            if not cluster.center_text:
                cluster.center_text = self.generate_center_text(cluster)
            cluster.ExpList = self.extract_experiences_for_cluster(cluster)

        return cluster

    def _check_cluster_consistency(self, qa_items: List[QAItem]) -> Dict[str, Any]:
        if not qa_items:
            return {"is_consistent": False, "confidence": 0.0, "reason": "empty cluster"}

        if len(qa_items) == 1:
            single = qa_items[0]
            return {
                "is_consistent": True,
                "confidence": 1.0,
                "reason": "single QA",
                "label": single.question[:50],
            }

        if self.llm_controller is None:
            return {"is_consistent": True, "confidence": 0.0, "reason": "llm unavailable"}

        qa_text = "\n\n".join(f"Q: {qa.question}\nA: {qa.answer}" for qa in qa_items)

        prompt = (
            "You are validating whether a group of question-answer pairs are about the same topic.\n"
            "Read the following QA samples and decide if they can be considered one coherent cluster.\n"
            "If they are consistent, optionally provide a short label summarizing the theme.\n"
            "Respond strictly in JSON.\n\n"
            "QA samples:\n"
            f"{qa_text}\n"
        )

        response_format = {
            "type": "json_schema",
            "json_schema": {
                "name": "cluster_consistency",
                "schema": {
                    "type": "object",
                    "properties": {
                        "is_consistent": {"type": "boolean"},
                        "confidence": {"type": "number"},
                        "reason": {"type": "string"},
                        "label": {"type": "string"}
                    },
                    "required": ["is_consistent", "confidence"],
                    "additionalProperties": False
                },
                "strict": True
            }
        }

        try:
            raw_resp = self.llm_controller.llm.get_completion(
                prompt=prompt,
                response_format=response_format,
                temperature=0.2,
            )
            parsed = self._safe_json_from_raw(raw_resp)
            if not parsed:
                return {"is_consistent": True, "confidence": 0.0, "reason": "unexpected llm output"}
        except Exception as exc:
            return {"is_consistent": True, "confidence": 0.0, "reason": f"llm_error: {exc}"}

        parsed.setdefault("is_consistent", True)
        parsed.setdefault("confidence", 0.0)
        return parsed

    def recompute_cluster_center(self, cluster_id: str, top_k: int = 3) -> None:
        cluster = self.get_cluster(cluster_id)
        if cluster is None:
            raise ValueError(f"cluster {cluster_id} not found")
        if not cluster.QAList:
            return

        emb_matrix = np.stack([qa.emb for qa in cluster.QAList], axis=0)
        vector_center = emb_matrix.mean(axis=0)
        cluster.vector_center = vector_center

        sims = [self.sim_fn(qa.emb, vector_center) for qa in cluster.QAList]
        sorted_idx = np.argsort(sims)[::-1]
        k = min(top_k, len(cluster.QAList))
        cluster.cluster_center = [cluster.QAList[i].id for i in sorted_idx[:k]]

    def generate_center_text(self, cluster: Cluster) -> str:
        if self.llm_controller is None:
            return ""

        cluster_qas = [f"Q: {qa.question}\nA: {qa.answer}" for qa in self.get_qas(cluster.id, strategy="all")]
        qa_text = "\n\n".join(cluster_qas)

        prompt = f"""Below is a set of semantically similar Q&A samples. 
Please summarize their central theme.

You MUST respond with a JSON object of the form:
{{
"center_text": "one or two sentences summary"
}}

Q&A samples for analysis:
{qa_text}
"""

        response_format = {
            "type": "json_schema",
            "json_schema": {
                "name": "response",
                "schema": {
                    "type": "object",
                    "properties": {"center_text": {"type": "string"}},
                    "required": ["center_text"],
                    "additionalProperties": False
                },
                "strict": True
            }
        }

        max_retries = 3
        last_resp = ""

        for attempt in range(max_retries):
            try:
                resp = self.llm_controller.llm.get_completion(prompt=prompt, response_format=response_format)
                last_resp = resp
                data = self._safe_json_from_raw(resp)
                center_text = str(data.get("center_text", "")).strip() if data else ""
                if center_text:
                    return center_text
                if attempt == max_retries - 1:
                    return str(last_resp).strip() or ""
            except Exception:
                if attempt == max_retries - 1:
                    return str(last_resp).strip() or ""
        return ""

    def extract_experiences_for_cluster(self, cluster: Cluster) -> List[ExperienceItem]:
        # (Keep original prompt and logic; no changes requested here)
        if self.llm_controller is None:
            return []

        qa_list = self.get_qas(cluster.id, strategy="all")
        indexed_qas = []
        for idx, qa in enumerate(qa_list):
            indexed_qas.append(f"[{idx}] Speaker={qa.speaker}\nQ: {qa.question}\nA: {qa.answer}")
        qa_context = "\n\n".join(indexed_qas)

        prompt = f"""
You extract reusable experiences from short dialogues.

You will see several Q&A items from the same semantic cluster.
Each item has an index like [0], [1], etc.

Dialogue samples:
{qa_context}

Your task:
- Extract a SMALL SET of reusable experiences that can help in similar future cases.
- Each experience must be directly supported by the dialogue (do not invent facts).
- Do NOT output vague life advice or generic statements.
- Prefer "fact" or "preference" when the dialogue states something directly.
- Only use "strategy" when the experience clearly generalizes beyond this specific person.
- Avoid generic strategies like "communicate more", "be kind", or "support is important".
- Only mark Q&A indices where the experience is explicitly expressed.
- It is better to output fewer, high-quality experiences than many weak or generic ones.
- content ≤ 120 characters.

Allowed types:
- fact: a stable fact likely to remain true
- strategy: a general reusable approach
- preference: a stable interest or habit

Few-shot example:

[0] Speaker=Alex
Q: I started weekly therapy recently.
A:
[1] Speaker=Ben
Q: Has it helped?
A:
[2] Speaker=Alex
Q: Yes, talking regularly helps me feel less overwhelmed.
A:

Example output:
{{
"experiences": [
    {{
    "type": "fact",
    "content": "Alex attends weekly therapy and feels less overwhelmed.",
    "source_qa_indices": [0, 2]
    }}
]
}}

Now output STRICT JSON for the current dialogue only:
{{
"experiences": [
    {{
    "type": "fact | strategy | preference",
    "content": "short experience (≤120 chars)",
    "source_qa_indices": [0, 1]
    }}
]
}}
""".strip()

        response_format = {
            "type": "json_schema",
            "json_schema": {
                "name": "cluster_experiences",
                "schema": {
                    "type": "object",
                    "properties": {
                        "experiences": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "type": {"type": "string", "enum": ["fact", "strategy", "preference"]},
                                    "content": {"type": "string", "maxLength": 120},
                                    "source_qa_indices": {"type": "array", "items": {"type": "integer"}}
                                },
                                "required": ["type", "content", "source_qa_indices"],
                                "additionalProperties": False
                            }
                        }
                    },
                    "required": ["experiences"],
                    "additionalProperties": False
                },
                "strict": True
            }
        }

        max_len = 120

        STOPWORDS = {"the", "and", "with", "have", "really", "very", "feel", "feels", "good", "nice", "cool", "help",
                     "helped", "been", "just", "like"}
        GREETING_PATTERNS = [r"good to see you", r"how have you been", r"how are you", r"what's up", r"\bhey\b",
                             r"\bhi\b", r"\bhello\b"]

        def is_small_talk(qa: QAItem) -> bool:
            text = f"{qa.question} {qa.answer}".lower()
            if not any(re.search(p, text) for p in GREETING_PATTERNS):
                return False
            stripped = text
            for p in GREETING_PATTERNS:
                stripped = re.sub(p, " ", stripped)
            tokens = re.findall(r"\w+", stripped)
            content_tokens = [t for t in tokens if t not in STOPWORDS]
            return len(content_tokens) <= 3

        experiences: List[ExperienceItem] = []
        data, _raw = self._llm_json(prompt=prompt, response_format=response_format, temperature=0.1, max_retries=5)
        if not data:
            return []

        items = data.get("experiences", []) or []
        seen_pairs = set()

        for item in items:
            etype = str(item.get("type", "fact")).strip()
            content = str(item.get("content", "")).strip()
            if len(content) > max_len:
                content = content[:max_len].rstrip()
            if not content:
                continue

            idx_list = item.get("source_qa_indices", []) or []
            filtered_idx_list = []
            for idx in idx_list:
                if isinstance(idx, str) and idx.strip().isdigit():
                    idx = int(idx.strip())
                if not (isinstance(idx, int) and 0 <= idx < len(qa_list)):
                    continue
                qa = qa_list[idx]
                if is_small_talk(qa):
                    continue
                filtered_idx_list.append(idx)

            if not filtered_idx_list:
                continue

            pair_key = (etype, content)
            if pair_key in seen_pairs:
                continue
            seen_pairs.add(pair_key)

            source_ids = [qa_list[i].id for i in filtered_idx_list]
            exp = ExperienceItem(
                id=str(uuid.uuid4()),
                type=etype,
                content=content,
                source_qa_ids=source_ids,
                metadata={"cluster_id": cluster.id},
            )
            experiences.append(exp)

        return experiences

    def extract_experiences_from_qas(
        self,
        qa_items: List[QAItem],
        eps: float = 0.3,
        min_samples: int = 2,
        max_recluster_rounds: int = 2,
    ) -> List[Cluster]:
        if not qa_items:
            return []

        def _clustering_func(emb_matrix: np.ndarray) -> List[int]:
            return dbscan_clustering_func(emb_matrix=emb_matrix, eps=eps, min_samples=min_samples)

        clusters = self.initial_clustering(
            qa_items=qa_items,
            clustering_func=_clustering_func,
            max_recluster_rounds=max_recluster_rounds,
        )
        return clusters

    # =========================
    # Incremental update (clusters)
    # =========================

    def incremental_experiences_from_qas(
        self,
        qa_items: List[QAItem],
        window_size: int = 4,
        sim_high: float = 0.8,
        sim_low: float = 0.5,
        eps: float = 0.3,
        min_samples: int = 2,
        max_recluster_rounds: int = 2,
        update_exp_threshold: int = 4,
    ) -> None:
        if not qa_items:
            return

        n = len(qa_items)
        for start in range(0, n, window_size):
            end = min(n, start + window_size)
            window_qas = qa_items[start:end]
            if not window_qas:
                continue

            if not self._clusters:
                self.extract_experiences_from_qas(
                    qa_items=window_qas,
                    eps=eps,
                    min_samples=min_samples,
                    max_recluster_rounds=max_recluster_rounds,
                )
            else:
                self._incremental_experience_update_round(
                    new_qas=window_qas,
                    window_size=window_size,
                    sim_high=sim_high,
                    sim_low=sim_low,
                    eps=eps,
                    min_samples=min_samples,
                    max_recluster_rounds=max_recluster_rounds,
                    update_exp_threshold=update_exp_threshold,
                )

    def _incremental_experience_update_round(
        self,
        new_qas: List[QAItem],
        window_size: int,
        sim_high: float = 0.8,
        sim_low: float = 0.5,
        eps: float = 0.3,
        min_samples: int = 2,
        max_recluster_rounds: int = 2,
        update_exp_threshold: int = 4,
    ) -> None:
        if not new_qas:
            return

        routed = self.incremental_route_qas(new_qas=new_qas, sim_high=sim_high, sim_low=sim_low)
        remained_after_mid = self._llm_assign_mid_qas(routed["mid_candidates"])
        self.pending_qas.extend(remained_after_mid)
        self.pending_qas.extend(routed["low_qas"])

        if len(self.pending_qas) > window_size:
            qa_items = self.pending_qas
            self.pending_qas = []
            self.extract_experiences_from_qas(
                qa_items=qa_items,
                eps=eps,
                min_samples=min_samples,
                max_recluster_rounds=max_recluster_rounds,
            )

        self._maybe_update_clusters_experiences(update_exp_threshold)

    def _maybe_update_clusters_experiences(self, update_exp_threshold: int) -> None:
        if update_exp_threshold is None or update_exp_threshold <= 0:
            return

        for cluster in self._clusters.values():
            if len(cluster.add_buffer) >= update_exp_threshold:
                self.recompute_cluster_center(cluster.id)
                if self.llm_controller is not None:
                    cluster.center_text = self.generate_center_text(cluster)
                    cluster.ExpList = self.extract_experiences_for_cluster(cluster)
                cluster.add_buffer.clear()

    # =========================
    # Experience retrieval (clusters-only)
    # =========================

    def rank_clusters_by_question_embedding(self, question: str, top_n: int = 5) -> List[Cluster]:
        if not self._clusters:
            return []
        q_emb = self.embed_text(question)
        sims: List[Tuple[Cluster, float]] = []
        for c in self._clusters.values():
            sim = self.sim_fn(q_emb, c.vector_center)
            sims.append((c, sim))
        sims.sort(key=lambda x: x[1], reverse=True)
        return [c for c, _ in sims[:top_n]]

    def rank_clusters_by_center_text_llm(self, question: str, top_n: int = 5) -> List[Cluster]:
        if not self._clusters or self.llm_controller is None:
            return []

        items = [{"cluster_id": c.id, "center_text": c.center_text} for c in self._clusters.values()]
        desc = "\n".join(f"- id: {it['cluster_id']}, center_text: {it['center_text']}" for it in items)

        prompt = f"""
You are a classification assistant. Given a user question Q and several candidate category descriptions (center_text), please select the most relevant categories.

Question Q:
{question}

Candidate Categories:
{desc}

Task: Based on the meaning of Q, select the most relevant categories and output their IDs as a list.

Output JSON format:
{{"cluster_ids": ["id1", "id2"]}}

Important: Only output valid cluster IDs that exist in the candidate list above.
"""

        response_format = {
            "type": "json_schema",
            "json_schema": {
                "name": "cluster_ranking",
                "schema": {
                    "type": "object",
                    "properties": {"cluster_ids": {"type": "array", "items": {"type": "string"}}},
                    "required": ["cluster_ids"],
                    "additionalProperties": False
                },
                "strict": True
            }
        }

        max_retries = 3
        for attempt in range(max_retries):
            try:
                temperature = 0.1
                current_prompt = prompt if attempt == 0 else (prompt + "\n\nNote: output strict JSON only.")
                raw = self.llm_controller.llm.get_completion(
                    prompt=current_prompt,
                    response_format=response_format,
                    temperature=temperature
                )
                data = self._safe_json_from_raw(raw)
                if not data:
                    continue
                cid_list = data.get("cluster_ids", []) or []
                clusters: List[Cluster] = []
                for cid in cid_list:
                    if cid in self._clusters:
                        clusters.append(self._clusters[cid])
                    if len(clusters) >= top_n:
                        break
                return clusters[:top_n]
            except Exception:
                time.sleep(1)
                continue
        return []

    def retrieve_experiences_for_question(
        self,
        question: str,
        top_n_clusters: int = 3,
        top_k_exps: int = 5,
    ) -> List[ExperienceItem]:
        embed_ranked = self.rank_clusters_by_question_embedding(question, top_n=top_n_clusters)
        llm_ranked = self.rank_clusters_by_center_text_llm(question, top_n=top_n_clusters)

        candidate_clusters: List[Cluster] = []
        seen = set()
        for c in embed_ranked + llm_ranked:
            if c.id not in seen:
                seen.add(c.id)
                candidate_clusters.append(c)

        if not candidate_clusters:
            return []

        q_emb = self.embed_text(question)
        scored_exps: List[Tuple[ExperienceItem, float]] = []
        for c in candidate_clusters:
            for exp in c.ExpList:
                exp_emb = self.embed_text(exp.content)
                sim = self.sim_fn(q_emb, exp_emb)
                scored_exps.append((exp, sim))

        if not scored_exps:
            return []

        scored_exps.sort(key=lambda x: x[1], reverse=True)
        return [exp for exp, _ in scored_exps[:top_k_exps]]

    # =========================
    # KG indexing & retrieval
    # =========================

    def _format_relation_text(self, rel: Relation, flag: bool) -> str:
        #True 返回meta信息，False 不返回
        src = self.kg.entities.get(rel.source)
        tgt = self.kg.entities.get(rel.target)
        src_name = src.name if src else rel.source
        tgt_name = tgt.name if tgt else rel.target

        meta = rel.metadata or {}
        time_str = meta.get("time", "")
        cond_str = meta.get("condition", "")

        extra_parts = []
        if time_str:
            extra_parts.append(f"time: {time_str}")
        if cond_str:
            extra_parts.append(f"condition: {cond_str}")
        
        extras = " | ".join(extra_parts) if extra_parts else ""
        if flag:
            base = f"{src_name} {rel.relation_type} {tgt_name}"
            return base if not extras else base + " | " + extras
        else:
            return f"{src_name} {rel.relation_type} {tgt_name}"

    def build_triple_index(self) -> None:
        texts = []
        ids = []
        for rid, rel in self.kg.relations.items():
            # keep: exclude only structural links that explode search space
            if rel.relation_type in ("contains", "about"):
                continue
            ids.append(rid)
            texts.append(self._format_relation_text(rel,False))

        if not texts:
            self._triple_ids = []
            self._triple_texts = []
            self._triple_embs = None
            self._triple_id2idx: Dict[str, int] = {}
            return

        self._triple_ids = ids
        self._triple_texts = texts
        self._triple_embs = self._embed_model.encode(texts)
        self._triple_id2idx = {rid: i for i, rid in enumerate(ids)}

    def retrieve_triples_for_question(self, question: str, top_k: int = 32) -> List[Relation]:
        if not self._triple_ids or self._triple_embs is None:
            return []

        q_emb = self.embed_text(question)
        sims = cosine_similarity([q_emb], self._triple_embs)[0]
        k = min(top_k, len(self._triple_ids))
        idxs = np.argsort(sims)[-k:][::-1]

        results = []
        for i in idxs:
            rid = self._triple_ids[i]
            rel = self.kg.relations.get(rid)
            if rel:
                results.append(rel)
        return results

    
    # ---- NEW: score-based triple selection (combines LLM judgment and embedding order) ----
    def score_triples_with_llm(
        self,
        question: str,
        relations: List[Relation],
    ) -> List[Relation]:
        """Select useful triples via LLM, but keep a wider, embed-sorted set.

        - LLM 负责挑出“最关键”的若干条（selected_ids）
        - 其余 slots 用 embedding 排名最高的 triples 补齐
        - 这样既不会太窄（纯 LLM 选太少），也不会太宽松（仍按相似度排序）
        """

        if not relations or self.llm_controller is None:
            # 没有 LLM 时直接返回原列表（调用方通常已按相似度排序）
            return relations

        items = [
            {"id": rel.id, "text": self._format_relation_text(rel, True)}
            for rel in relations
        ]

        triples_text = "\n".join(
            f"- id: {it['id']}, triple: {it['text']}" for it in items
        )

        prompt = f"""
You are given a question and candidate knowledge graph triples.

Question:
{question}

Candidate triples:
{triples_text}

Task:
Select the triples that are MOST USEFUL to answer the question.

Guidelines:
- Only select triples that directly answer the question or provide strong supporting evidence.
- Do NOT include weakly related or background-only triples.
- If none are useful, return an empty list.

Return STRICT JSON:
{{
  "selected_ids": ["triple_id_1", "triple_id_2"]
}}
""".strip()

        # 允许 LLM 选更多一些（上限 16 条），实际数量再由下游控制
        response_format = {
            "type": "json_schema",
            "json_schema": {
                "name": "triple_select",
                "schema": {
                    "type": "object",
                    "properties": {
                        "selected_ids": {
                            "type": "array",
                            "maxItems": 16,
                            "items": {"type": "string"},
                        }
                    },
                    "required": ["selected_ids"],
                    "additionalProperties": False,
                },
                "strict": True,
            },
        }

        data, _ = self._llm_json(
            prompt=prompt,
            response_format=response_format,
            temperature=0.1,
            max_retries=3,
        )

        selected_ids: set[str] = set()
        if isinstance(data, dict):
            for tid in data.get("selected_ids", []) or []:
                tid = str(tid).strip()
                if tid:
                    selected_ids.add(tid)

        # relations 本身已经按 embedding 相似度排序，保持该顺序
        selected: List[Relation] = []
        seen: set[str] = set()

        # 1) 先放入 LLM 明确选中的 triples
        for r in relations:
            if r.id in selected_ids and r.id not in seen:
                selected.append(r)
                seen.add(r.id)

        # 2) 如果太少，用 embedding 排名最高的若干条补齐
        #    下限：至少保留 min_keep 条（不超过 relations 总数）
        min_keep = min(max(8, len(relations) // 2), len(relations))
        if len(selected) < min_keep:
            for r in relations:
                if r.id in seen:
                    continue
                selected.append(r)
                seen.add(r.id)
                if len(selected) >= min_keep:
                    break

        # 3) 为了避免过宽，整体做一个温和的上限
        max_keep = min(16, len(relations))
        return selected[:max_keep]

    def _get_time_hint_for_qa_id(self, qa_id: str) -> str:
        qid = (qa_id or "").strip()
        if not qid:
            return ""

        # cache hit
        if hasattr(self, "_qa_time_hint_cache") and qid in self._qa_time_hint_cache:
            return self._qa_time_hint_cache[qid]

        # scan relations once (can be heavy; cache saves repeated cost)
        candidates: List[str] = []
        for rel in self.kg.relations.values():
            meta = rel.metadata or {}
            if str(meta.get("qa_id") or "").strip() != qid:
                continue
            tval = str(meta.get("time") or "").strip()
            if tval:
                candidates.append(tval)

        # pick a "best" time (prefer normalized/longer time strings)
        best = ""
        if candidates:
            # 去重保持顺序
            uniq = []
            seen = set()
            for t in candidates:
                if t not in seen:
                    seen.add(t)
                    uniq.append(t)

            # 优先选择包含数字的（更像 normalized_time），再选最长的
            digit_first = [t for t in uniq if any(ch.isdigit() for ch in t)]
            pool = digit_first or uniq
            best = max(pool, key=lambda x: len(x))

        # write cache
        self._qa_time_hint_cache[qid] = best
        return best


    def _format_passage_doc(self, d: PassageDoc) -> str:
        # 1) 尝试从 PassageDoc 自身拿
        sp = (d.speaker or "").strip()
        ts = (d.timestamp or "").strip()

        # 2) 检索阶段兜底：从 qa_meta 补 speaker/timestamp（不改构建阶段）
        qid = (d.qa_id or "").strip()

        time_hint = ""
        if qid:
            time_hint = self._get_time_hint_for_qa_id(qid)

        if qid and hasattr(self, "_qa_meta") and isinstance(self._qa_meta, dict):
            meta = self._qa_meta.get(qid) or {}
            if not sp:
                sp = (meta.get("speaker") or "").strip()
            if not ts:
                ts = (meta.get("timestamp") or "").strip()

        # 3) 如果仍然没有 speaker，给个明确占位（避免出现 “[ts | ]”）
        if not sp:
            sp = "Unknown"

        prefix = f"[{ts} | {sp}] " if (ts or sp) else ""
        suffix = f" (time_hint: {time_hint})" if time_hint else ""
        return f"{prefix}{d.text}{suffix}".strip()


    def _prefilter_relations_by_embed(
        self,
        question: str,
        relations: List[Relation],
        k: int = 36,
    ) -> List[Relation]:
        if not relations:
            return []
        if self._triple_embs is None:
            return relations

        q_emb = self.embed_text(question)

        # 直接从全局 triple embedding 里取子集
        idx_map = getattr(self, "_triple_id2idx", {})
        idxs_all = []
        rel_list: List[Relation] = []
        for r in relations:
            idx = idx_map.get(r.id)
            if idx is None:
                continue
            idxs_all.append(idx)
            rel_list.append(r)

        if not idxs_all:
            return relations

        sub_embs = self._triple_embs[idxs_all]
        sims = cosine_similarity([q_emb], sub_embs)[0]
        topk = min(k, len(rel_list))
        order = np.argsort(sims)[-topk:][::-1]
        return [rel_list[i] for i in order]


    def graph_retrieve_passages(
        self,
        question: str,
        top_k_triples: int = 6,
        max_hop: int = 1,
        max_passages: int = 6,
        max_experiences: int = 6,
        global_passage_k: int = 12,   # global passage retrieval side channel（更宽一些）
    ) -> Tuple[str, str]:

        if self._triple_embs is None or not self._triple_ids:
            self.build_triple_index()
        if self._triple_embs is None or not self._triple_ids:
            # still allow global passage retrieval
            return "", self._global_passage_context(question, k=global_passage_k)

        # 0) retrieve seed triples
        seed_rels = self.retrieve_triples_for_question(question=question, top_k=top_k_triples)
        if not seed_rels:
            return "", self._global_passage_context(question, k=global_passage_k)

        # 1) expand 1-hop in entity subgraph
        seed_entity_ids: set[str] = set()
        for rel in seed_rels:
            seed_entity_ids.add(rel.source)

            seed_entity_ids.add(rel.target)

        cand_relation_ids: set[str] = set(r.id for r in seed_rels)

        for eid in list(seed_entity_ids):
            sub = self.kg.get_neighbour(
                eid,
                max_hop=max_hop,
                include_passages=False,
                include_experiences=False,
            )
            for r in sub["relations"]:
                cand_relation_ids.add(r.id)

        candidate_rels = []
        for rid in cand_relation_ids:
            rel = self.kg.relations.get(rid)
            if rel and rel.relation_type not in ("contains", "about"):
                candidate_rels.append(rel)

        if not candidate_rels:
            # fallback: just use seed rels
            candidate_rels = seed_rels
    
        candidate_rels = self._prefilter_relations_by_embed(question, candidate_rels, k=36)
        

        ########临时打印########
        # lines=[]
        # print(question)
        # for rel in candidate_rels:
        #     head=self.kg.entities.get(rel.source)
        #     tail=self.kg.entities.get(rel.target)
        #     print( head.name,rel.relation_type,tail.name,rel.metadata.get("time",""))
        
        print("-----")



        # final_rels = self.score_triples_with_llm(
        #     question=question,
        #     relations=candidate_rels,
        # )
        final_rels = candidate_rels  # 暂时不使用 LLM 评分，直接用 embed 排序结果
        if not final_rels:
            final_rels = candidate_rels[: min(3, len(candidate_rels))]
            if not final_rels:
                final_rels = seed_rels[: min(3, len(seed_rels))]

        # 最终兜底
        if not final_rels:
            final_rels = seed_rels[: min(3, len(seed_rels))]




        # --- 去重 KG 三元组：同一个 (head, relation, tail, time) 只保留一次 ---
        def _dedup_relations(rels: List[Relation]) -> List[Relation]:
            seen = set()
            out: List[Relation] = []
            for r in rels:
                time_val = ""
                try:
                    time_val = str((r.metadata or {}).get("time", "")).strip()
                except Exception:
                    time_val = ""
                key = (r.source, r.target, r.relation_type, time_val)
                if key in seen:
                    continue
                seen.add(key)
                out.append(r)
            return out

        final_rels = _dedup_relations(final_rels)

        # 2) collect entities from final triples
        final_entity_ids: set[str] = set()
        for rel in final_rels:
            final_entity_ids.add(rel.source)
            final_entity_ids.add(rel.target)

        q_emb = self.embed_text(question)

        kg_passage_docs: List[PassageDoc] = []
        exp_candidates: List[str] = []

        # -------- collect KG-linked passages / experiences --------
        for eid in final_entity_ids:
            for rid in self.kg.in_edges.get(eid, []):
                rel = self.kg.relations.get(rid)
                if not rel:
                    continue

                if rel.relation_type == "contains":
                    src = self.kg.entities.get(rel.source)
                    if src and src.metadata.get("node_type") == "passage":
                        txt = (src.name or "").strip()
                        if not txt:
                            continue

                        qa_id = str(src.metadata.get("qa_id") or "").strip()
                        if not qa_id:
                            continue  

                        # timestamp 优先用 QA meta（更一致）；否则用 passage 节点里的 timestamp
                        ts = str(src.metadata.get("timestamp") or "").strip()
                        speaker = None
                        if qa_id in getattr(self, "_qa_meta", {}):
                            speaker = (self._qa_meta[qa_id].get("speaker") or "").strip() or None
                            qa_ts = (self._qa_meta[qa_id].get("timestamp") or "").strip()
                            if qa_ts:
                                ts = qa_ts

                        kg_passage_docs.append(PassageDoc(
                            text=txt,
                            timestamp=ts,
                            speaker=speaker,
                            qa_id=qa_id,
                        ))

                elif rel.relation_type == "about":
                    src = self.kg.entities.get(rel.source)
                    if src and src.metadata.get("node_type") == "experience":
                        txt = (src.name or "").strip()
                        if txt:
                            exp_candidates.append(txt)

        # -------- dedup KG passages：优先按 qa_id，其次按 text --------
        def dedup_docs_kg(docs: List[PassageDoc]) -> List[PassageDoc]:
            seen_ids = set()
            seen_texts = set()
            out: List[PassageDoc] = []
            for d in docs:
                qid = (d.qa_id or "").strip()
                txt = (d.text or "").strip()

                if qid:
                    if qid in seen_ids:
                        continue
                    seen_ids.add(qid)
                else:
                    if txt in seen_texts:
                        continue
                    seen_texts.add(txt)

                out.append(d)
            return out

        kg_passage_docs = dedup_docs_kg(kg_passage_docs)

        # -------- rank docs by sim (use text embedding) --------
        def rank_docs_by_sim(docs: List[PassageDoc]) -> List[PassageDoc]:
            if not docs:
                return []
            # key 优先 qa_id，没有就用文本本身
            keys = [ (d.qa_id or d.text).strip() for d in docs ]
            texts = [ d.text for d in docs ]
            embs = self._get_cached_embs(keys, texts)
            sims = cosine_similarity([q_emb], embs)[0]
            idxs = np.argsort(sims)[::-1]
            return [docs[i] for i in idxs]

        kg_ranked = rank_docs_by_sim(kg_passage_docs)

        # -------- select passages --------
        # 新策略：
        # - 全局检索的 passage 至少 2 条（若可用）
        # - 其余优先用 KG passage
        # - 如果 KG+全局仍不足 max_passages，则继续从两侧补满到 max_passages

        selected: List[PassageDoc] = []
        selected_qa_ids: set[str] = set()

        # 先拿全局检索结果（多取一些，方便后续补齐）
        global_ranked = self._global_passage_list(
            question,
            k=max(global_passage_k, max_passages * 3),
        )

        # (1) 全局检索：尽量先拿到 2 条不重复 qa_id 的 passage
        mandatory_global: List[PassageDoc] = []
        for d in global_ranked:
            if d.qa_id in selected_qa_ids:
                continue
            mandatory_global.append(d)
            selected_qa_ids.add(d.qa_id)
            if len(mandatory_global) >= 2:
                break

        selected.extend(mandatory_global)

        # (2) KG passage：在剩余配额内优先补 KG 里的 passage
        for d in kg_ranked:
            if len(selected) >= max_passages:
                break
            if d.qa_id in selected_qa_ids:
                continue
            selected.append(d)
            selected_qa_ids.add(d.qa_id)

        # (3) 如果还没达到 max_passages，先从全局再从 KG 补齐
        if len(selected) < max_passages:
            for d in global_ranked:
                if len(selected) >= max_passages:
                    break
                if d.qa_id in selected_qa_ids:
                    continue
                selected.append(d)
                selected_qa_ids.add(d.qa_id)

        if len(selected) < max_passages:
            for d in kg_ranked:
                if len(selected) >= max_passages:
                    break
                if d.qa_id in selected_qa_ids:
                    continue
                selected.append(d)
                selected_qa_ids.add(d.qa_id)

        # --- 最终对 selected passages 再按内容去重：同一段文本仅保留一次 ---
        def _dedup_passages_by_text(docs: List[PassageDoc]) -> List[PassageDoc]:
            seen = set()
            out: List[PassageDoc] = []
            for d in docs:
                key = (d.text or "").strip()
                if key in seen:
                    continue
                seen.add(key)
                out.append(d)
            return out

        selected = _dedup_passages_by_text(selected)

        # -------- experiences keep your old logic (dedup + rerank) --------
        def dedup_str(xs: List[str]) -> List[str]:
            seen = set()
            out = []
            for x in xs:
                if x not in seen:
                    seen.add(x)
                    out.append(x)
            return out

        exp_candidates = dedup_str(exp_candidates)

        def topk_by_sim_str(cands: List[str], k: int) -> List[str]:
            if not cands:
                return []
            keys = [ s.strip() for s in cands ]   # experience 没 id，就直接用文本做 key
            embs = self._get_cached_embs(keys, cands)
            sims = cosine_similarity([q_emb], embs)[0]
            idxs = np.argsort(sims)[-min(k, len(cands)):][::-1]
            return [cands[i] for i in idxs]

        graph_exps = topk_by_sim_str(exp_candidates, max_experiences)

        # -------- output --------
        kg_context_text = "\n".join(self._format_relation_text(r, True) for r in final_rels)

        blocks: List[str] = []
        if selected:
            lines = [f"- {self._format_passage_doc(d)}" for d in selected]
            blocks.append("Passages:\n" + "\n".join(lines))
        if graph_exps:
            blocks.append("Experiences:\n" + "\n".join(f"- {t}" for t in graph_exps))

        text_context = "\n\n".join(blocks) if blocks else ""
        return kg_context_text, text_context

    def _global_passage_list(self, question: str, k: int = 6) -> List[PassageDoc]:
        # 现在 retriever.search 直接返回 PassageDoc 列表
        return self.retriever.search(question, k=k)

    def _global_passage_context(self, question: str, k: int = 6) -> str:
        docs = self._global_passage_list(question, k=k)
        if not docs:
            return ""
        return "Passages:\n" + "\n".join(f"- {self._format_passage_doc(d)}" for d in docs)

    # =========================
    # KG extraction
    # =========================

    def _llm_extract_entity_names_from_question(self, question: str) -> List[str]:
        if self.llm_controller is None:
            return []

        prompt, response_format = extract_ent_prompt(question)  # noqa: F405
        data, _raw = self._llm_json(prompt=prompt, response_format=response_format, temperature=0.2, max_retries=3)
        if not data:
            return []

        entities = data.get("entities", []) or []
        names: List[str] = []
        for entity in entities:
            if isinstance(entity, str):
                e = entity.strip()
                if e:
                    names.append(e)

        seen = set()
        unique: List[str] = []
        for name in names:
            if name not in seen:
                seen.add(name)
                unique.append(name)

        return unique

    def _match_entity_name_in_kg(self, name: str, fuzzy_threshold: float = 0.7) -> Optional[Entity]:
        ent = self.kg.get_entity(name)
        if ent is not None:
            return ent

        if not self.kg.name_index:
            return None

        target_norm = name.strip().lower()
        best_score = 0.0
        best_eid = None

        for norm_name, eid in self.kg.name_index.items():
            score = difflib.SequenceMatcher(None, target_norm, norm_name).ratio()
            if score > best_score:
                best_score = score
                best_eid = eid

        if best_eid is not None and best_score >= fuzzy_threshold:
            return self.kg.entities.get(best_eid)
        return None

    def _match_entity_names_in_kg(
        self,
        names: List[str],
        fuzzy_threshold: float = 0.7,
        max_matched: int = 3,
    ) -> List[Entity]:
        matched: List[Entity] = []
        seen_ids = set()
        for name in names:
            ent = self._match_entity_name_in_kg(name, fuzzy_threshold=fuzzy_threshold)
            if ent is not None and ent.id not in seen_ids:
                seen_ids.add(ent.id)
                matched.append(ent)
            if len(matched) >= max_matched:
                break
        return matched
    
    def _enrich_relations_with_context(
        self,
        dialogue_text: str,
        relations_basic: list[dict],
        max_tries: int = 2,
    ) -> list[dict]:

        if not relations_basic or self.llm_controller is None:
            return []

        enriched_relations: list[dict] = []

        for r in relations_basic:
            relation_desc = f"source: {r['source']}, relation_type: {r['relation_type']}, target: {r['target']}"

            # 直接抽取“归一化后的时间”（如果没有就返回空）
            time_prompt, time_response_format = extract_time_prompt(  
                dialogue_text=dialogue_text,
                relation_desc=relation_desc,
            )

            data, _raw = self._llm_json(
                prompt=time_prompt,
                response_format=time_response_format,
                temperature=0.1,
                max_retries=max_tries,
            )

            abs_time = ""
            if isinstance(data, dict):
                abs_time = str(data.get("absolute_time", "")).strip()

            enriched_relations.append(
                {
                    "source": r["source"],
                    "target": r["target"],
                    "relation_type": r["relation_type"],
                    "time": abs_time,
                    "condition": r["condition"]
                }
            )

        return enriched_relations


    def _extract_entities_and_relations_with_retry(
        self,
        window_text: str,
        max_tries: int = 3,
    ) -> List[dict]:
        if self.llm_controller is None:
            return []

        last_relations: List[dict] = []

        for _attempt in range(max_tries):
            ent_prompt, ent_response_format = extract_ent_prompt(window_text)  # noqa: F405
            ent_data, _ent_raw = self._llm_json(
                prompt=ent_prompt,
                response_format=ent_response_format,
                temperature=0.2,
                max_retries=1,
            )
            if not ent_data:
                continue

            raw_entities: List[str] = ent_data.get("entities", []) or []
            clean_entities: List[str] = []
            seen = set()
            for e in raw_entities:
                if not isinstance(e, str):
                    continue
                name = e.strip()
                if not name:
                    continue
                key = name.lower()
                if key in seen:
                    continue
                seen.add(key)
                clean_entities.append(name)

            if not clean_entities:
                last_relations = []
                continue


            entity_list_text = ", ".join(clean_entities)
            rel_prompt, rel_response_format = extract_rel_prompt(window_text, entity_list_text)  # noqa: F405

            rel_basic_data, _rel_raw = self._llm_json(
                prompt=rel_prompt,
                response_format=rel_response_format,
                temperature=0.4,
                max_retries=1,
            )
            if not rel_basic_data:
                last_relations = []
                continue

            relations_basic: List[dict] = rel_basic_data.get("relations", []) or []

            clean_relations_basic: List[dict] = []
            entity_set = {e.strip() for e in clean_entities}
            for r in relations_basic:
                if not isinstance(r, dict):
                    continue
                s = str(r.get("source", "")).strip()
                t = str(r.get("target", "")).strip()
                rt = str(r.get("relation_type", "")).strip()
                c = str(r.get("condition", "")).strip()
                if not (s and t and rt):
                    continue
                if s not in entity_set or t not in entity_set:
                    continue
                clean_relations_basic.append({"source": s, "target": t, "relation_type": rt, "condition": c})

            if not clean_relations_basic:
                last_relations = []
                continue

            final_relations = self._enrich_relations_with_context(
                dialogue_text=window_text,
                relations_basic=clean_relations_basic,
                max_tries=2,
            )
            last_relations = final_relations
            return final_relations

        return last_relations

    def extract_kg_from_qa_windows(
        self,
        qa_items: List[QAItem],
        max_retries: int = 3,
        session_id: Optional[str] = None,
    ) -> None:

        if not qa_items or self.llm_controller is None:
            return

        session_entity_ids: set[str] = set()
        session_relation_ids: set[str] = set()

        def safe_get_string(data: Dict, key: str) -> str:
            value = data.get(key)
            if value is None:
                return ""
            if isinstance(value, str):
                return value.strip()
            if isinstance(value, list) and value:
                first_item = value[0]
                if isinstance(first_item, str):
                    return first_item.strip()
                if isinstance(first_item, (int, float)):
                    return str(first_item).strip()
                return ""
            if isinstance(value, (int, float)):
                return str(value).strip()
            return ""

        for qa in qa_items:
            # 每个 QA 自带时间戳
            dialogue_timestamp = qa.timestamp or datetime.utcnow().isoformat()

            # 原文文本（你可以保持这个格式）
            window_text = f"Date/Time: {dialogue_timestamp}\nSpeaker {qa.speaker} says: {qa.question}"

            # Create passage node for the *center* qa only
            passage_id = self.kg.add_passage_node(
                text=qa.question,
                metadata={"source": "dialog", "timestamp": dialogue_timestamp, "qa_id": qa.id, "speaker": qa.speaker},
            )

            raw_relations = self._extract_entities_and_relations_with_retry(
                window_text=window_text,
                max_tries=max_retries,
            )

            if not raw_relations:
                continue

            relations: List[dict] = []
            for r in raw_relations:
                relations.append(
                    {
                        "source": r.get("source", ""),
                        "target": r.get("target", ""),
                        "relation_type": r.get("relation_type", ""),
                        "metadata": {
                            "time": r.get("time", ""),
                            "condition": r.get("condition", ""),
                        },
                    }
                )

            entities: set[str] = set()
            for rel in relations:
                s_name = safe_get_string(rel, "source")
                t_name = safe_get_string(rel, "target")
                if s_name:
                    entities.add(s_name)
                if t_name:
                    entities.add(t_name)

            local_entity_cache: Dict[str, str] = {}
            name_norm_to_id: Dict[str, str] = {}

            for name in entities:
                if not isinstance(name, str) or not name.strip():
                    continue
                norm = name.lower()

                if norm in local_entity_cache:
                    eid = local_entity_cache[norm]
                else:
                    existing = self.kg.get_entity(name)
                    if existing is not None:
                        eid = existing.id
                    else:
                        eid = self.kg.get_or_add_entity(
                            name=name,
                            metadata={"source": "dialog", "node_type": "entity"},
                        )
                    local_entity_cache[norm] = eid

                name_norm_to_id[norm] = eid
                session_entity_ids.add(eid)

                # passage -> entity contains
                self.kg.add_relation(
                    source_id=passage_id,
                    target_id=eid,
                    relation_type="contains",
                    metadata={"timestamp": dialogue_timestamp},
                )

            # entity-entity relations
            for rel in relations:
                s_name = safe_get_string(rel, "source")
                t_name = safe_get_string(rel, "target")
                r_type = safe_get_string(rel, "relation_type")
                if not (s_name and t_name and r_type):
                    continue

                s_id = name_norm_to_id.get(s_name.lower()) or (self.kg.get_entity(s_name).id if self.kg.get_entity(s_name) else None)
                t_id = name_norm_to_id.get(t_name.lower()) or (self.kg.get_entity(t_name).id if self.kg.get_entity(t_name) else None)
                if s_id is None or t_id is None:
                    continue

                metadata = rel.get("metadata", {})
                if not isinstance(metadata, dict):
                    metadata = {}

                # store provenance
                if session_id is not None:
                    metadata.setdefault("session_id", session_id)
                metadata.setdefault("qa_id", qa.id)
                metadata.setdefault("passage_id", passage_id)

                rid = self.kg.add_relation(
                    source_id=s_id,
                    target_id=t_id,
                    relation_type=r_type,
                    metadata=metadata,
                )
                session_relation_ids.add(rid)
                session_entity_ids.add(s_id)
                session_entity_ids.add(t_id)



        # Session-level review (existing) + dynamic merge suggestions (new)
        if session_entity_ids or session_relation_ids:
            self._review_and_complete_kg_for_dialogue(
                dialogue_timestamp=dialogue_timestamp,
                qa_items=qa_items,
                session_entity_ids=session_entity_ids,
                session_relation_ids=session_relation_ids,
                session_id=session_id,
                max_retries=max_retries,
            )

    def _review_and_complete_kg_for_dialogue(
        self,
        dialogue_timestamp: str,
        qa_items: List[QAItem],
        session_entity_ids: set[str],
        session_relation_ids: set[str],
        session_id: Optional[str] = None,
        max_retries: int = 3,
    ) -> None:
        """
        Keep original ADD/UPDATE/DENY review behavior (prompt unchanged; uses review_kg_prompt from prompt.py).
        """
        if self.llm_controller is None or not qa_items:
            return

        dialogue_lines = []
        for qa in qa_items:
            speaker = qa.speaker or "Speaker"
            dialogue_lines.append(f"{speaker}: {qa.question}")
        full_dialogue_text = "\n".join(dialogue_lines)

        entities_desc = []
        session_entity_name_map = {}
        for eid in session_entity_ids:
            ent = self.kg.entities.get(eid)
            if not ent:
                continue
            entities_desc.append({"id": ent.id, "name": ent.name})
            session_entity_name_map[ent.name.strip().lower()] = ent.id

        relations_desc = []
        for rid in session_relation_ids:
            rel = self.kg.relations.get(rid)
            if not rel:
                continue
            src = self.kg.entities.get(rel.source)
            tgt = self.kg.entities.get(rel.target)
            src_name = src.name if src else rel.source
            tgt_name = tgt.name if tgt else rel.target
            meta = rel.metadata or {}
            relations_desc.append(
                {
                    "id": rel.id,
                    "source": src_name,
                    "target": tgt_name,
                    "relation_type": rel.relation_type,
                    "time": meta.get("time", ""),
                    "condition": meta.get("condition", ""),
                }
            )

        if not relations_desc and not entities_desc:
            return

        relations_text_lines = []
        for r in relations_desc:
            base = f"id={r['id']} {r['source']} {r['relation_type']} {r['target']}"
            extra = []
            if r["time"]:
                extra.append(f"time={r['time']}")
            if r["condition"]:
                extra.append(f"condition={r['condition']}")
            if extra:
                base += " | " + "; ".join(extra)
            relations_text_lines.append(" - " + base)
        relations_text = "\n".join(relations_text_lines)

        entities_text = "\n".join(
            f"- id={e['id']}, name={e['name']}"
            for e in entities_desc
        )

        # prompt from prompt.py (unchanged)
        prompt, response_format = review_kg_prompt( 
            full_dialogue_text=full_dialogue_text,
            entities_text=entities_text,
            relations_text=relations_text,
            dialogue_timestamp=dialogue_timestamp,
        )

        data, _raw = self._llm_json(prompt=prompt, response_format=response_format, temperature=0.1, max_retries=max_retries)
        if not data:
            return

        add_list = data.get("add", []) or []
        update_list = data.get("update", []) or []
        deny_list = data.get("deny", []) or []

        def _resolve_entity(name: str) -> Entity:
            norm = name.strip().lower()
            if norm in session_entity_name_map:
                eid = session_entity_name_map[norm]
                return self.kg.entities[eid]
            ent = self._match_entity_name_in_kg(name)
            if ent is not None:
                return ent
            return self.kg.entities[self.kg.get_or_add_entity(
                name=name,
                metadata={"source": "session_review", "node_type": "entity", "aliases": []},
            )]

        # ADD
        for item in add_list:
            try:
                src_name = (item.get("source") or "").strip()
                tgt_name = (item.get("target") or "").strip()
                rel_type = (item.get("relation_type") or "").strip()
                if not (src_name and tgt_name and rel_type):
                    continue

                src_ent = _resolve_entity(src_name)
                tgt_ent = _resolve_entity(tgt_name)

                meta = {
                    "time": (item.get("time") or "").strip(),
                    "condition": (item.get("condition") or "").strip(),
                }
                if session_id is not None:
                    meta["session_id"] = session_id
                    meta.setdefault("source", "session_review")

                rid = self.kg.add_relation(
                    source_id=src_ent.id,
                    target_id=tgt_ent.id,
                    relation_type=rel_type,
                    metadata=meta,
                )
                
            except Exception:
                continue

        # UPDATE
        for item in update_list:
            try:
                rid = (item.get("relation_id") or "").strip()
                if not rid:
                    continue
                rel = self.kg.relations.get(rid)
                if not rel:
                    continue

                new_type = (item.get("relation_type") or "").strip()
                if new_type:
                    rel.relation_type = new_type

                for key in ("time",  "condition"):
                    if key in item:
                        rel.metadata[key] = (item.get(key) or "").strip()

                
            except Exception:
                continue

        # DENY
        for item in deny_list:
            try:
                rid = (item.get("relation_id") or "").strip()
                if not rid:
                    continue
                rel = self.kg.relations.pop(rid, None)
                if not rel:
                    continue
                if rid in self.kg.out_edges.get(rel.source, []):
                    self.kg.out_edges[rel.source].remove(rid)
                if rid in self.kg.in_edges.get(rel.target, []):
                    self.kg.in_edges[rel.target].remove(rid)
            except Exception:
                continue

        try:
            self.kg.dedup_relations_ignore_condition(keep="first", include_time=True)
            self.build_triple_index()
            
        except Exception:
            pass

    # =========================
    # Experience subgraph rebuild (unchanged)
    # =========================

    def clear_experience_subgraph(self):
        exp_entity_ids = [eid for eid, ent in self.kg.entities.items() if ent.metadata.get("node_type") == "experience"]
        if not exp_entity_ids:
            return

        rel_to_delete = set()
        for rid, rel in self.kg.relations.items():
            if rel.source in exp_entity_ids or rel.target in exp_entity_ids:
                rel_to_delete.add(rid)

        for rid in rel_to_delete:
            rel = self.kg.relations.pop(rid, None)
            if not rel:
                continue
            if rid in self.kg.out_edges.get(rel.source, []):
                self.kg.out_edges[rel.source].remove(rid)
            if rid in self.kg.in_edges.get(rel.target, []):
                self.kg.in_edges[rel.target].remove(rid)

        for eid in exp_entity_ids:
            self.kg.entities.pop(eid, None)
            self.kg.out_edges.pop(eid, None)
            self.kg.in_edges.pop(eid, None)

    def _get_entities_for_qa_ids(self, qa_ids: List[str]) -> List[Entity]:
        if not qa_ids or not self.kg.entities or not self.kg.relations:
            return []

        qa_id_set = set(qa_ids)
        passage_ids = []
        for eid, ent in self.kg.entities.items():
            if ent.metadata.get("node_type") == "passage" and ent.metadata.get("qa_id") in qa_id_set:
                passage_ids.append(eid)

        if not passage_ids:
            return []

        entity_ids = set()
        for pid in passage_ids:
            for rid in self.kg.out_edges.get(pid, []):
                rel = self.kg.relations.get(rid)
                if not rel:
                    continue
                tgt_ent = self.kg.entities.get(rel.target)
                if tgt_ent and tgt_ent.metadata.get("node_type") == "entity":
                    entity_ids.add(tgt_ent.id)

        return [self.kg.entities[eid] for eid in entity_ids if eid in self.kg.entities]

    def rebuild_experience_subgraph_from_clusters(self):
        self.clear_experience_subgraph()
        if not self._clusters:
            return

        for cluster in self._clusters.values():
            if not cluster.ExpList:
                continue

            for exp in cluster.ExpList:
                exp_eid = self.kg.add_experience_node(
                    text=exp.content,
                    metadata={"cluster_id": cluster.id, "type": exp.type},
                )

                kg_entities = self._get_entities_for_qa_ids(exp.source_qa_ids)
                for ent in kg_entities:
                    self.kg.add_relation(
                        source_id=exp_eid,
                        target_id=ent.id,
                        relation_type="about",
                        metadata={"cluster_id": cluster.id},
                    )

    def rebuild_retriever_from_qas(self, qa_items: List[QAItem]) -> None:
        """
        不重建KG，只用 QAItems 重建全局检索器（带 speaker/timestamp）。
        同时缓存 qa_id -> speaker/timestamp，供 KG-linked passage 结果补全 speaker。
        """
        self.retriever.clear()
        self._qa_meta = {}

        if not qa_items:
            return

        docs: List[PassageDoc] = []
        for qa in qa_items:
            if not qa or not isinstance(qa.question, str) or not qa.question.strip():
                continue
            ts = str(qa.timestamp or "").strip()
            sp = str(qa.speaker or "").strip() or None
            qid = str(qa.id)

            self._qa_meta[qid] = {"speaker": sp or "", "timestamp": ts}

            docs.append(PassageDoc(
                text=qa.question.strip(),
                timestamp=ts,
                speaker=sp,
                qa_id=qid,
            ))

        self.retriever.add_docs(docs)


    # =========================
    # Incremental routing (unchanged prompts)
    # =========================

    def incremental_route_qas(
        self,
        new_qas: List[QAItem],
        sim_high: float = 0.8,
        sim_low: float = 0.5,
    ) -> Dict[str, Any]:
        high_assigned = []
        mid_candidates = []
        low_qas = []

        if not new_qas or not self._clusters:
            return {"high_assigned": [], "mid_candidates": [], "low_qas": new_qas}

        for qa in new_qas:
            best_id = None
            best_sim = -1.0
            sims_for_all: List[Tuple[str, float]] = []

            for cid, cluster in self._clusters.items():
                sim = self.sim_fn(qa.emb, cluster.vector_center)
                sims_for_all.append((cid, sim))
                if sim > best_sim:
                    best_sim = sim
                    best_id = cid

            sims_for_all.sort(key=lambda x: x[1], reverse=True)
            top5 = [cid for cid, s in sims_for_all[:5] if s >= sim_low]

            if best_id is not None and best_sim >= sim_high:
                cluster = self._clusters[best_id]
                cluster.QAList.append(qa)
                cluster.add_buffer.append(qa)
                high_assigned.append((best_id, qa))
            elif top5:
                mid_candidates.append({"qa": qa, "candidate_clusters": top5})
            else:
                low_qas.append(qa)

        return {"high_assigned": high_assigned, "mid_candidates": mid_candidates, "low_qas": low_qas}

    def _llm_assign_mid_qas(self, mid_candidates: List[Dict[str, Any]]) -> List[QAItem]:
        if not mid_candidates or self.llm_controller is None:
            return [item["qa"] for item in mid_candidates]

        remained_qas: List[QAItem] = []

        def safe_json_parse(json_str: str) -> Dict:
            import sys
            original_recursion_limit = sys.getrecursionlimit()
            try:
                sys.setrecursionlimit(max(original_recursion_limit, 5000))
                if not json_str.strip():
                    return {}
                text = json_str.strip()
                if "{" in text and "}" in text:
                    start = text.find("{")
                    end = text.rfind("}") + 1
                    if start >= 0 and end > start:
                        text = text[start:end]
                text = text.replace('\n', ' ').replace('\r', ' ')
                text = re.sub(r',\s*}', '}', text)
                text = re.sub(r',\s*]', ']', text)
                return json.loads(text)
            except Exception:
                return {}
            finally:
                sys.setrecursionlimit(original_recursion_limit)

        for item in mid_candidates:
            qa: QAItem = item["qa"]
            cids: List[str] = item["candidate_clusters"]

            descs = []
            for cid in cids:
                cluster = self._clusters[cid]
                sample_questions = " | ".join(q.question for q in self.get_qas(cid, "sample"))
                descs.append(
                    f"- cluster_id: {cid}\n"
                    f"  center_text: {cluster.center_text}\n"
                    f"  example_questions: {sample_questions}"
                )

            prompt = f"""
Given a dialogue and several candidate clusters, please determine whether the new dialogue belongs to any of these clusters.

New Dialogue:
{qa.question + " " + qa.answer}

Candidate Clusters:
{chr(10).join(descs)}

Output Requirements:
- If the new dialogue belongs to one of the clusters, provide the corresponding cluster_id
- If it doesn't fit any cluster, return "none"

Please output in JSON format:
{{"cluster_id": "cluster_id_value or none"}}

Important: Keep the response simple and use valid JSON format only.
"""
            response_format = {
                "type": "json_schema",
                "json_schema": {
                    "name": "cluster_choice",
                    "schema": {
                        "type": "object",
                        "properties": {"cluster_id": {"type": "string"}},
                        "required": ["cluster_id"],
                        "additionalProperties": False
                    },
                    "strict": True
                }
            }

            max_retries = 3
            assigned = False

            for attempt in range(max_retries):
                try:
                    current_prompt = prompt if attempt == 0 else f"""
Please choose a cluster for this dialogue or return "none".

Dialogue: {qa.question}

Available clusters:
{chr(10).join([f"- {cid}: {self._clusters[cid].center_text[:100]}..." for cid in cids])}

Output JSON: {{"cluster_id": "cluster_id or none"}}
"""
                    raw = self.llm_controller.llm.get_completion(
                        prompt=current_prompt,
                        response_format=response_format,
                        temperature=0.1
                    )
                    data = safe_json_parse(raw) if isinstance(raw, str) else (raw if isinstance(raw, dict) else {})
                    if not data:
                        if attempt < max_retries - 1:
                            continue
                        break

                    cid = data.get("cluster_id", "none")
                    if cid != "none" and cid in self._clusters:
                        cluster = self._clusters[cid]
                        cluster.QAList.append(qa)
                        cluster.add_buffer.append(qa)
                        assigned = True
                        break
                    else:
                        break
                except Exception:
                    if attempt < max_retries - 1:
                        continue
                    break

            if not assigned:
                remained_qas.append(qa)

        return remained_qas


def run_tests():
    pass


if __name__ == "__main__":
    run_tests()
